src/Entity/Notes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotesRepository")
 */
class Notes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getOwner(): ?Users
    {
        return $this->owner;
    }

    public function setOwner(?Users $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

templates/app/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Edit
{% endblock %}

{% block stylesheets %}
	{{parent()}}
	<link href="/styles/app.css" rel="stylesheet">
{% endblock %}

{% block body %}
	{{form_start(update, {'attr': {'class': 'edit-form'}})}}
	<a href="{{path('homepage')}}">
		Back
	</a>
	{{form_row(update.content)}}
	{{form_row(update.created)}}
	{{form_row(update.owner)}}
	{{form_widget(update.submit)}}
	{{form_end(update)}}
{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Notes App
{% endblock %}

{% block stylesheets %}
	{{parent()}}
	<link href="/styles/app.css" rel="stylesheet">
{% endblock %}

{% block body %}
	<div class="appContent">
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class='alert alert-{{label}}'>
					{{message|raw}}
				</div>
			{% endfor %}
		{% endfor %}
		<div class="user">
			<div class='new-form'>
				<form action="{{path('newNote')}}" method="POST">
					<label for='new-content'>
						<input type='text' name='content' class='new-input' id='new-content' required>
					</label>
					<input type='submit' value='Make new note'>
				</form>
			</div>
			<p>
				<span>
					Hello
					{% if app.user.name %}
						{{app.user.name|capitalize}}
					{% else %}
						{{app.user.username}}
					{% endif %}
				</span>
				<a href="{{path('logout')}}">
					Logout
				</a>
			</p>
		</div>
		<div class="data" id="notes">
			{% for note in app.user.notes|sort((a, b) => b.createdAt|date('Y-m-d H:i:s') <=> a.createdAt|date('Y-m-d H:i:s')) %}
				<div class='note'>
					<p class='content'>
						{{note.content|raw}}
					</p>
					<p class='date'>
						{{note.createdAt|date('d-m-Y')}}
					</p>
					<a href="{{path('editNote', {'id': note.id})}}">
						Edit
					</a>
					<p class='delete' data-id={{note.id}}>
						Delete
					</p>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script src="/js/delete.js"></script>
{% endblock %}